
import '@/styles/globals.css';
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div className='desktop:px-35 desktop:py-20'>
          {children}
        </div>
      </body>
    </html>
  );
}
